name: trilingo
description: A Flutter app for Trilingo
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.5
  cupertino_icons: ^1.0.3
  http: ^1.1.0
  provider: ^6.0.5
  google_sign_in: ^6.1.4
  flow_builder: ^0.1.0
  line_icons: ^2.0.1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  image_picker: ^1.0.2
  animated_bottom_navigation_bar: ^1.1.0+1
  intl: ^0.20.2
  animated_background: ^2.0.0
  flutter_animate: ^4.2.0
  google_fonts: ^6.2.1
  win32: ^4.1.3 
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3
  cloud_firestore: ^5.0.0
  lottie: ^3.1.0
  font_awesome_flutter: ^10.7.0
 


  
  # Add other dependencies here

flutter:
  uses-material-design: true
  assets:
    - assets/images/Trilingo-image.png
    - assets/images/Trilingo-icon.png
    - assets/images/hotel_booking.png
    - assets/images/language_translator.png
    - assets/images/food_beverages.png
    - assets/images/flight_booking.png
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-hdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
    - ios/Runner/Assets.xcassets/AppIcon.appiconset/
    - assets/images/49svh_2.png
    - assets/images/welcome_image.png
    - assets/images/ai_chatbot.png
    - assets/images/google-icon.png
    - assets/images/Homescreenimage.png
    - assets/images/loginpage.png
    - assets/images/signuppage.png
    - assets/animations/main1.mp4
    - assets/animations/main2.mp4
    - assets/animations/main3.mp4
    - assets/animations/main4.mp4
    - assets/animations/main5.mp4


    # Add other asset paths here

dev_dependencies:
  flutter_test:
    sdk: flutter

fonts:
  - family: MaterialIcons
    fonts:
      - asset: fonts/MaterialIcons-Regular.ttf    
dependency_overrides:
  win32: 4.1.3