name: trilingo
description: A Flutter app for Trilingo
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.5
  cupertino_icons: ^1.0.3
  http: ^1.1.0
  provider: ^6.0.5
  google_sign_in: ^6.1.4
  flow_builder: ^0.0.9
  line_icons: ^2.0.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  image_picker: ^1.0.2
  animated_bottom_navigation_bar: ^1.1.0+1
  intl: ^0.17.0
 


  
  # Add other dependencies here

flutter:
  uses-material-design: true
  assets:
    - assets/images/Trilingo-image.png
    - assets/images/hotel_booking.png
    - assets/images/language_translator.png
    - assets/images/food_beverages.png
    - assets/images/flight_booking.png
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-hdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
    - ios/Runner/Assets.xcassets/AppIcon.appiconset/
    - assets/images/49svh_2.png
    - assets/images/welcome_image.png
    - assets/images/ai_chatbot.png


    # Add other asset paths here

dev_dependencies:
  flutter_test:
    sdk: flutter

fonts:
  - family: MaterialIcons
    fonts:
      - asset: fonts/MaterialIcons-Regular.ttf    
