name: trilingo
description: A Flutter app for Trilingo
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.5
  cupertino_icons: ^1.0.3
  firebase_auth: ^4.7.2
  http: ^0.13.3
  provider: ^5.0.0
  firebase_core: ^2.15.0
  google_sign_in: ^6.1.4
  # Add other dependencies here

flutter:
  assets:
    - assets/images/Trilingo-image.png
    - assets/images/hotel_booking.png
    - assets/images/language_translator.png
    - assets/images/food_beverages.png
    - assets/images/flight_booking.png

    # Add other asset paths here

dev_dependencies:
  flutter_test:
    sdk: flutter
